{{- if .Values.istioService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "appname" . }}-{{ include "orgname" . }}
  labels:
    {{- include "hlf-chaincode.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ default "cc" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}"
  gateways:
    - mesh
  tcp:
    - route:
        - destination:
            host: {{ default "cc" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.istioService.port }}
          weight: 100
{{- end }}
