apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-{{ include "appname" . }}-{{ include "orgname" . }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - hosts:
    - {{ $.Values.fqdn }}
    port:
      name: https-ext-auth
      number: 8443
      protocol: HTTPS
    tls:
      httpsRedirect: false
      mode: PASSTHROUGH
