apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ include "appname" . }}-{{ include "orgname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  gateways:
  - gw-{{ .Release.Namespace }}
  hosts:
  - {{ .Values.fqdn }}
  tls:
  - match:
      - port: 8443
        sniHosts:
          - {{ .Values.fqdn }}
    route:
    - destination:
        host: {{ default "auth-server" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8443
      weight: 100
