---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-aws-credentials
  namespace: argocd
type: Opaque
stringData:
  credentials: |
    [{{ .Values.aws_profile }}]
    aws_access_key_id = {{ .Values.aws_access_key_id }}
    aws_secret_access_key = {{ .Values.aws_secret_access_key }}
  config: |
    [profile {{ .Values.aws_profile }}]
    region = {{ .Values.region }}
