{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
{{/*  finalizers:*/}}
{{/*  - resources-finalizer.argocd.argoproj.io*/}}
spec:
  project: {{ $.Values.global.project }}
  source:
    path: {{ .path }}
  {{- with $.Values.global.source }}
    {{- toYaml . | nindent 4 }}
  {{- end}}
    {{ if .useSecretFile }}
    helm:
      valueFiles:
        - values.yaml
        - secrets.yaml
    {{ end }}
  {{- with $.Values.global.destination }}
  destination:
    {{- toYaml . | nindent 4 }}
  {{- end}}
    namespace: {{ .namespace}}
  {{- with $.Values.global.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end}}
---
{{- end }}
