apiVersion: v1
kind: Service
metadata:
  name: {{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
  labels:
    {{- include "hlf-explorer.labels" . | nindent 4 }}
    svc.hkicl/name: {{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "hlf-explorer.selectorLabels" . | nindent 4 }}
    app.hkicl/name: {{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
