# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: sa-{{ include "appname" . }}
  namespace: {{ .Release.Namespace }}
