apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ include "appname" . }}-{{ include "orgname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redisearch.labels" . | nindent 4 }}
spec:
  gateways:
    - mesh
  hosts:
    - "{{ default "redisearch" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}"
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: {{ .Values.appname }}-{{.Values.orgname }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 6379
          weight: 100
    - match:
        - port: 9121
      route:
        - destination:
            host: {{ .Values.appname }}-{{.Values.orgname }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 9121
          weight: 100
