{{- if .Values.peersEnabled }}
{{- range .Values.peers }}
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: peer0-{{ .targetOrg }}
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
    - "peer0-{{ .targetOrg }}.{{ $.Values.domainName }}"
  ports:
    - number: 7051
      protocol: TLS
      name: tls-req
      targetPort: 7051
  location: {{ default "MESH_EXTERNAL" .location }}
  resolution: {{ default "STATIC" .resolution }}
  {{- if eq .resolution "STATIC" }}
  endpoints:
    - address: {{ .address }}
  {{- end }}
---
{{- end }}
{{- end }}
