{{- if .Values.peersEnabled }}
{{- range .Values.peers }}
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ default "peer0" .peerName }}-{{ .targetOrg }}
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
    - {{ default "peer0" .peerName }}-{{ .targetOrg }}.{{ $.Values.domainName }}
  ports:
    - number: 7051
      protocol: GRPC
      name: grpc-req
      targetPort: 7051
  location: {{ default "MESH_EXTERNAL" .location }}
  resolution: {{ default "STATIC" .resolution }}
  {{- if eq .resolution "STATIC" }}
  endpoints:
    - address: {{ .address }}
  {{- end }}
---
{{- end }}
{{- end }}
