{{- if .Values.peersEnabled }}
{{- range .Values.peers }}
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ default "peer0" .peerName }}-{{ .targetOrg }}
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
    - {{ default "peer0" .peerName }}-{{ .targetOrg }}.{{ $.Values.domainName }}
  ports:
    {{- if eq .protocol "GRPC" }}
    - number: {{ default "7051" .port }}
      protocol: GRPC
      name: grpc-req
      targetPort: {{ default "7051" .port }}
  {{- else if eq .protocol "TLS" }}
    - number: {{ default "7051" .port }}
      protocol: TLS
      name: tls-req
      targetPort: {{ default "7051" .port }}
  {{- else if eq .protocol "HTTPS" }}
    - number: {{ default "7051" .port }}
      protocol: HTTPS
      name: https-req
      targetPort: {{ default "7051" .port }}
  {{- else if eq .protocol "HTTP" }}
    - number: {{ default "7051" .port }}
      protocol: HTTP
      name: http-req
      targetPort: {{ default "7051" .port }}
  {{- else }}
    - number: {{ default "7051" .port }}
      protocol: TCP
      name: tcp-req
      targetPort: {{ default "7051" .port }}
  {{- end }}
  location: {{ default "MESH_EXTERNAL" .location }}
  resolution: {{ default "STATIC" .resolution }}
  {{- if eq .resolution "STATIC" }}
  endpoints:
    - address: {{ .address }}
  {{- end }}
---
{{- end }}
{{- end }}
