orgname: ORGNAME
database_username: DATABASE_USERNAME
database_passwd: DATABASE_PASSWORD

image:
  # -- Fixture
  # @default -- internal value
  pullPolicy: IfNotPresent

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 5Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/var/explorer"
  # existingClaim: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

# -- Fixture
# @default -- internal value
appname: explorer-db

# -- Fixture
# @default -- internal value
replicaCount: 1

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Fixture
# @default -- internal value
podAnnotations: {}

# -- Fixture
# @default -- internal value
podSecurityContext: {}
# fsGroup: 2000

# -- Fixture
# @default -- internal value
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tcp-postgresql

# -- Fixture
# @default -- internal value
configmap:
  enabled: true
  data: "config/*"
  mountPath: "/setup"

# -- Fixture
# @default -- internal value
affinity: {}

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
istioService:
  enabled: true
  ports:
    - port: 5432
      name: tcp-postgresql
      protocol: TCP
      destPort: 5432
