apiVersion: v2
name: service-entry
version: 0.1.13
description: Helper charts to deploy service-entry for peers or orderers
type: application
appVersion: 0.0.2
icon: "https://raw.githubusercontent.com/rtang03/rtang03/main/dashslab_icon.jpg"
maintainers:
  - name: "rtang03"
    email: "ask@dashslab.com"
annotations:
  artifacthub.io/changes: |
    - "add peer1 service entry"
  artifacthub.io/prerelease: "true"
