apiVersion: v2
name: jaeger
version: 0.1.21
description: Jaeger tracing tool
type: application
appVersion: "1.27.0"
icon: "https://raw.githubusercontent.com/rtang03/rtang03/main/dashslab_icon.jpg"
sources:
  - https://istio.io/latest/docs/ops/integrations/jaeger/#configuration
maintainers:
  - name: "rtang03"
    email: "ask@dashslab.com"
annotations:
  artifacthub.io/changes: |
    - "add ports"
  artifacthub.io/prerelease: "true"
