#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME

# -- Fixture
# @default -- internal value
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "14269"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 1Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/badger"

# -- Fixture
# @default -- internal value
appname: jaeger
