#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: bochk

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "14269"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: "/badger"

#######################
### FIXTURE         ###
#######################
appname: jaeger
