#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME

# -- Fixture
# @default -- internal value
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "14269"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 1Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/badger"

# -- Fixture
# @default -- internal value
appname: jaeger

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: http-query
    - port: 16685
      targetPort: 16685
      protocol: TCP
      name: grpc-query
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http-zipkin
    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: collector-http
    - port: 14250
      targetPort: 14250
      protocol: TCP
      name: collector-grpc
