# Application Name
appname: prometheus
orgname: org1
namespace: n1

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi
  mountPath: "/data"

podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

securityContext: {}

# Prometheus consumes at least 512 Mi
resources:
  requests:
    cpu: 300m
    memory: 640Mi
  limits:
    cpu: 500m
    memory: 1000Mi

prometheus:
  global:
    evaluation_interval: 1m
    scrape_interval: 15s
    scrape_timeout: 10s

scrapes:
  istio:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer0:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer1:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer2:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer3:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer4:
    enabled: true
  # Eligible for ALL orgs
  hyperledgerPeer0:
    enabled: true
  # Eligible for ALL orgs
  hyperledgerPeer1:
    enabled: true
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisearchPrometheusExporter:
    enabled: false
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisExporter:
    enabled: false
