# -- Organization name
orgname: ORGNAME

# -- namespace of Scrape targets
namespace: NAMESPACE

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 20Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/data"

# Prometheus consumes at least 512 Mi
resources:
  requests:
    cpu: 100m
    memory: 640Mi
  limits:
    cpu: 400m
    memory: 1500Mi

prometheus:
  global:
    evaluation_interval: 1m
    scrape_interval: 15s
    scrape_timeout: 10s

scrapes:
  istio:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer0:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer1:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer2:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer3:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer4:
    enabled: false
  # Eligible for ALL orgs
  hyperledgerPeer0:
    enabled: true
  # Eligible for ALL orgs
  hyperledgerPeer1:
    enabled: true
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisearchPrometheusExporter:
    enabled: true
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisExporter:
    enabled: true

# -- Fixture
# @default -- internal value
appname: prometheus

# -- Fixture
# @default -- internal value
podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

# -- Fixture
# @default -- internal value
securityContext: {}
