#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME
namespace: NAMESPACE

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 20Gi
  mountPath: "/data"

# Prometheus consumes at least 512 Mi
resources:
  requests:
    cpu: 100m
    memory: 640Mi
  limits:
    cpu: 400m
    memory: 1500Mi

prometheus:
  global:
    evaluation_interval: 1m
    scrape_interval: 15s
    scrape_timeout: 10s

scrapes:
  istio:
    enabled: true
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer0:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer1:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer2:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer3:
    enabled: false
  # Eligible for Org 0/1 deployment
  hyperledgerOrderer4:
    enabled: false
  # Eligible for ALL orgs
  hyperledgerPeer0:
    enabled: true
  # Eligible for ALL orgs
  hyperledgerPeer1:
    enabled: true
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisearchPrometheusExporter:
    enabled: true
  # Eligible for OrgX, NOT for Org 0/1 deployment
  redisExporter:
    enabled: true

#######################
### FIXTURE         ###
#######################
appname: prometheus

podSecurityContext:
  fsGroup: 65534
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

securityContext: {}
