#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME
orgAdminSecret: xxxxx

# e.g. 'uat-ORGNAME.cdi.network'
# -- fqdn used by istio gateway / VS
fqdn: https://example.com

orderers:
  # -- Fixture
  # @default -- internal value
  - name: orderer0-org0
    # e.g. grpcs://orderer0-org0.cdi.testnet:7050
    # -- fqdn for orderer
    url: grpcs://o0.org0.com:7050
  - name: orderer1-org0
    # e.g. grpcs://orderer1-org0.cdi.testnet:7050
    # -- fqdn for orderer
    url: grpcs://o1.org0.com:7050
  - name: orderer2-org0
    # e.g. grpcs://orderer2-org0.cdi.testnet:7050
    # -- fqdn for orderer
    url: grpcs://o2.org0.com:7050
  - name: orderer3-org0
    # e.g. grpcs://orderer3-org0.cdi.testnet:7050
    # -- fqdn for orderer
    url: grpcs://o3.org0.com:7050
  - name: orderer4-org0
    # e.g. grpcs://orderer4-org0.cdi.testnet:7050
    # -- fqdn for orderer
    url: grpcs://o4.org0.com:7050

# e.g. 'https://uat-ORGNAME.cdi.network:8443/oauth/authenticate'
# -- url to oauth/auth endpoint
authorizationServerUri: https://example.com

# -- Fixture
# @default -- internal value
caEnrollmentIdAdmin: ca-admin

# -- format: enrollment-ca-ORGNAME
caName: enrollment-ca-ORG

# -- Channel name
channelName: cdi-testnet

# e.g. uat-ORGNAME.cdi.network
# -- fqdn for gateway, used by istio VS / gateway
gatewayHost: https://example.com

# -- info | debug
logLevel: debug

# -- MSP ID
mspid: MSPID

# -- Organization admin ID
orgAdminId: myadmin

# e.g. 'https://enrollmentca-ORGNAME:7054'
# -- fqdn for enrollment CA
orgCaUrl: https://example.com

# e.g. 'https://uat-ORGNAME.cdi.network:4101/gw_org'
# -- fqdn for Gateway app; must use port 4101
orgUrl: https://example.com

# -- istio VS or k8s service
redisHost: redisearch-ORGNAME

timezone: 'Asia/Hong_Kong'

nodeTLSRejectUnauthorized:
  enabled: false
  value: "0"

# -- only supported "Bearer"
dataAccessHeaderAuthType: Bearer

# e.g. https://uat-TARGET_ORGNAME.cdi.network/apigw/gw/s2s/thirdparty/v1/SaleTransaction/fileUrls
# -- No info
dataAccessApigwUrl: https://example.com

# e.g. https://uat-TARGET_ORGNAME.cdi.network/datafile/
# -- No info
dataAccessMappedUrl: https://example.com

# -- Emali Consent Flow App Param
aclOrgId: CDI_PARTICIPANT_000001

# -- Fixture
# @default -- internal value
aclFile: /assets/acl.json

# e.g. 'https://uat-ORGNAME.cdi.network:8443/account/login'
# -- used by Init Container
authCheckUrl: https://example.com

# -- used by Init Container
authCheckReply: Unauthorized

# test cert
# certPathCert: /cert/test-cdi-network.crt
# certPathKey: /cert/test-cdi-network.key
# caPathCert: /cert/test-cacert.crt

# -- No info
debugPlaceholder: queryHandler:* ioredis:redis gw-lib:*

nodeSelector: {}
# node.hkicl/nodename: node2

revisionHistoryLimit: 15

image:
  repository: hktfp5/cdi-samples
  imageBase: gw-data-consumer
  pullPolicy: IfNotPresent
  appVersion: 0.4.5

podAnnotations:
  # -- Fixture
  # @default -- internal value
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
  # trace|debug|info|warning|error|critical|off
  sidecar.istio.io/logLevel: "warning"

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 50Mi
  # -- Fixture
  # @default -- internal value
  mountPath: "/assets"
  # existingClaim: ""

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 3Gi

# -- Fixture
# @default -- internal value
replicaCount: 1

# -- Fixture
# @default -- internal value
appname: gw

# -- Fixture
# @default -- internal value
certPathCert: /cert/tls.crt

# -- Fixture
# @default -- internal value
certPathKey: /cert/tls.key

# -- Fixture
# @default -- internal value
caPathCert: /cert/rootca.crt

# -- Fixture
# @default -- internal value
administratorPort: 15011

# -- Fixture
# @default -- internal value
queryPort: 5001

# -- Fixture
# @deprecated -- internal value
gatewayPort: 4101

# -- Fixture
# @default -- internal value
redisPort: 6379

# -- Fixture
# @default -- internal value
wallet: /assets/wallet

# -- Fixture
# @default -- internal value
orgKey: /assets/orgkey

# -- Fixture
# @default -- internal valu
connectionProfile: /home/app/connection.yaml

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: http-gw
    - port: 4101
      targetPort: 4101
      protocol: TCP
      name: https-gw

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
affinity: {}

## Note: need to :4101/healthcheck. The below logic may not work
## Let do it later
#livenessProbe:
#  successThreshold: 1
#  failureThreshold: 3
#  httpGet:
#    scheme: HTTP
#    path: /healthcheck
#    port: 4001
#  initialDelaySeconds: 20
#  periodSeconds: 10
#
#readinessProbe:
#  successThreshold: 1
#  failureThreshold: 3
#  httpGet:
#    scheme: HTTP
#    path: /healthcheck
#    port: 4001
#  initialDelaySeconds: 20
#  periodSeconds: 10
