#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME
# -- MSP ID
mspid: MSPID
# -- Channel name
channel_name: cdi-testnet
# -- network name for use in Explorer only, can be any name
network_name: cdi_testnet
# -- url for addressable peer
peer_url: grpcs://peer0-ORGNAME.cdi.testnet:7051
# -- url of CA server (istio VS or k8s service)
ca_url: https://enrollment-ca-ORGNAME:7054
database_username: DATABASE_USERNAME
database_passwd: DATABASE_PASSWORD
# -- info | debug
log_level_app: info
# -- info | debug
log_level_db: info
# -- info | debug
log_level_console: info
# -- sync interval by minute
blocksSyncTime: 5

# -- Fixture
# @default -- internal value
replicaCount: 1

image:
  # -- Fixture
  # @default -- internal value
  pullPolicy: IfNotPresent

pgbouncer:
  tag: 1.15.0

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations:
  # -- Fixture
  # @default -- internal value
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
  # -- trace|debug|info|warning|error|critical|off
  sidecar.istio.io/logLevel: "warning"

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 1Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/opt/explorer/wallet/cdi"
  # existingClaim: ""

# -- Fixture
# @default -- internal value
appname: explorer

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-explorer

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# -- Fixture
# @default -- internal value
affinity: {}

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
secretvol:
  vol:
    - name: msp-admin
      mountPath: /secret/msp-admin
    - name: tls-peer0
      mountPath: /secret/tls-peer0
    - name: explorer-login-token
      mountPath: /secret/tokens

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
istioService:
  enabled: true
  ports:
    - port: 8080
      name: http-ext
      protocol: HTTP
      destPort: 8080
