apiVersion: v2
name: redisearch-prometheus-exporter
version: 0.1.3
description: "Export Redisearch FT.INFO for use by Prometheus.Supports RediSearch >=v2.0"
type: application
appVersion: 0.0.2
icon: "https://raw.githubusercontent.com/rtang03/rtang03/main/dashslab_icon.jpg"
sources:
  - https://github.com/rtang03/redisearch_prometheus_exporter
maintainers:
  - name: "rtang03"
    email: "ask@dashslab.com"
annotations:
  artifacthub.io/changes: |
    - "use helm-docs"
  artifacthub.io/prerelease: "true"
