#########################################################################
### CONFIGURABLE                                                      ###
### Note: values.schema.json is based on configurable items only.      ###
#########################################################################
orgname: ORGNAME
redisearchExporterStaticIndex: "cidx,eidx:Consent,eidx:user,eidx:participantDs,eidx:DataRequest,eidx:organization"

image:
  pullPolicy: IfNotPresent

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 64Mi

#######################
### FIXTURE         ###
#######################
appname: redisearch-prometheus-exporter

replicaCount: 1

service:
  type: ClusterIP
  ports:
    - port: 9122
      targetPort: 9122
      protocol: TCP
      name: tcp-exporter

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: [ ]

livenessProbe: {}

readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
