# -- Organization name
orgname: ORGNAME
# e.g. "cidx,eidx:Consent,eidx:user,eidx:participantDs,eidx:DataRequest,eidx:organization"
# -- Indexes to export
redisearchExporterStaticIndex: "cidx"

image:
  pullPolicy: IfNotPresent

# -- Fixture
# @default -- internal value
podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 50m
    memory: 64Mi

# -- Fixture
# @default -- internal value
appname: redisearch-prometheus-exporter

# -- Fixture
# @default -- internal value
replicaCount: 1

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 9122
      targetPort: 9122
      protocol: TCP
      name: tcp-exporter

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
imagePullSecrets: [ ]

# -- Fixture
# @default -- internal value
livenessProbe: {}

# -- Fixture
# @default -- internal value
readinessProbe: {}

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
nodeSelector: {}

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
affinity: {}
