apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ .Values.appname }}-{{ .Values.orgname }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  gateways:
  - gw-{{ .Release.Namespace }}
  - mesh
  hosts:
  - {{ .Values.fqdn | quote }}
  tls:
    - match:
        - port: {{ .Values.service.httpsPort }}
          sniHosts:
            - {{ .Values.fqdn }}
      route:
        - destination:
            host: nginx.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.targetPort.https }}
          weight: 100