# Source: prometheus/templates/server/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "server"
    app: prometheus
    release: prometheus
    chart: prometheus-{{ .Chart.Version }}
    heritage: Helm
  name: {{ include "appname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {}
