{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ include "appname" . }}-{{ include "orgname" . }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.configmap.data).AsConfig | indent 2 }}
{{- end }}
