apiVersion: v1
kind: Service
metadata:
  name: {{ include "appname" . }}-{{ include "orgname" . }}
  labels:
    {{- include "hlf-peer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
    # used by gupload sidecar
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-nginx
  {{- end }}
  selector:
    {{- include "hlf-peer.selectorLabels" . | nindent 4 }}
