{{- if .Values.istioService.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
  labels:
    app: hlf-peer
    version: {{ .Chart.Version }}
    {{- include "hlf-peer.labels" . | nindent 4 }}
    vs.hkicl/name: vs-{{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
spec:
  gateways:
  - gw-{{ include "hkicl.appname" . }}-{{ include "hkicl.orgname" . }}
  - mesh
  hosts:
  - {{ .Values.fqdn }}
  tls:
  {{- range .Values.istioService.ports }}
  {{ if or (eq "HTTPS" .protocol) (eq "TLS" .protocol) }}
  - match:
    - port: {{ .port }}
      sniHosts:
      - {{ $.Values.fqdn }}
    route:
    - destination:
        host: {{ default "hlf-peer" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}.{{ $.Values.namespace }}.svc.cluster.local
        port:
          number: {{ .destPort }}
      weight: 100
  {{ end }}
  {{- end }}
  http:
  {{- range .Values.istioService.ports }}
  {{ if eq "HTTP" .protocol }}
  - match:
    {{- toYaml .match | nindent 4}}
    route:
    - destination:
        host: {{ default "hlf-peer" $.Values.appname }}-{{ default "default-org" $.Values.orgname }}.{{ $.Values.namespace }}.svc.cluster.local
        port:
          number: {{ .destPort }}
      weight: 100
  {{ end }}
  {{- end }}
{{- end }}
