apiVersion: v2
name: argo-app-of-apps
description: Parent app, with app-of-app pattern
type: application
version: 0.1.3
appVersion: 0.4.4
icon: "https://raw.githubusercontent.com/rtang03/rtang03/main/dashslab_icon.jpg"
maintainers:
  - name: "rtang03"
    email: "ask@dashslab.com"
