global:
  # -- project name
  project: projectName

  # -- base path to the application charts
  appBasePath: app-core/argo-app-of-apps

  source:
    # -- url of git source
    repoURL: repoUrl
    # -- branch name of git source
    targetRevision: branchName

  destination:
    # -- namespace of this App-of-Apps
    namespace: namespace
    # -- installation target
    server: targetServerUrl

  syncPolicy:
    automated:
      # -- Fixture
      # @default -- internal value
      prune: true
      # -- Fixture
      # @default -- internal value
      selfHeal: true
