apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  {{- include "common.labels.standard" . | nindent 4 }}
spec:
  hosts:
    - postgres-postgresql-headless
  tcp:
    - route:
        - destination:
            host: postgres-postgresql-headless.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5432
          weight: 100
