apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jaeger.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        sidecar.istio.io/inject: "false"
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.27"
          env:
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: SPAN_STORAGE_TYPE
              value: "badger"
            - name: BADGER_DIRECTORY_VALUE
              value: "/badger/data"
            - name: BADGER_DIRECTORY_KEY
              value: "/badger/key"
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: MEMORY_MAX_TRACES
              value: "50000"
            - name: QUERY_BASE_PATH
              value: /jaeger
          livenessProbe:
            httpGet:
              path: /
              port: 14269
          readinessProbe:
            httpGet:
              path: /
              port: 14269
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if and .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: pvc-{{ include "appname" . }}-{{ include "orgname" . }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
