orgname: ORGNAME

config:
  maxmemory: 1000mb

timezone: 'Asia/Hong_Kong'

podAnnotations:
  # -- Fixture
  # @default -- internal value
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
  # -- trace|debug|info|warning|error|critical|off
  sidecar.istio.io/logLevel: "warning"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 1Gi

nodeSelector:
  node.hkicl/nodename: node3

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 1000Mi
  # -- Fixture
  # @default -- internal value
  mountPath: "/data"

redisExporterTag: 1.29.0

# -- Fixture
# @default -- internal value
replicaCount: 1

# -- Fixture
# @default -- internal value
appname: redisearch

image:
  repository: redislabs/redisearch
  pullPolicy: IfNotPresent

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

redisExporter:
  repository:  oliver006/redis_exporter
  # -- Fixture
  # @default -- internal value
  service:
    port: 9121
    protocol: TCP
    name: tcp-exporter

# -- Fixture
# @default -- internal value
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Fixture
# @default -- internal value
podSecurityContext: {}
# fsGroup: 2000

# -- Fixture
# @default -- internal value
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp-redis
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: tcp-red-exp

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
affinity: {}
