apiVersion: v2
name: grafana
# source coming from https://istio.io/latest/docs/ops/integrations/grafana/#configuration
version: 0.1.1
description: grafana
type: application
appVersion: 8.2.2
annotations:
  artifacthub.io/changes: |
    - kind: "fixed"
      description: "1st attempt fixing"
      links:
        - name: "improve security rating"
          url: "https://github.com/rtang03/helm-charts/issues/8"
  artifacthub.io/maintainers: |
    - name: "rtang03"
      email: "ask@dashslab.com"
