# Application Name
appname: grafana
orgname: org1
namespace: n1

podAnnotations: {}

podSecurityContext:
  fsGroup: 472
  runAsGroup: 472
  runAsUser: 472

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

persistence:
  enabled: true
  annotations: {}
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: "/var/lib/grafana"

configmap:
  json:
    - name: "istio-service-dashboard"
      filename: "config/istio-service-dashboard_rev93.json"
      mountPath: "/var/lib/grafana/dashboards/istio/istio-service-dashboard_rev93.json"
      subPath: "istio-service-dashboard_rev93.json"
    - name: "istio-workload-dashboard"
      filename: "config/istio-workload-dashboard_rev93.json"
      mountPath: "/var/lib/grafana/dashboards/istio/istio-workload-dashboard_rev93.json"
      subPath: "istio-workload-dashboard_rev93.json"
    - name: "istio-control-plane-dashboard"
      filename: "config/istio-control-plane-dashboard_rev93.json"
      mountPath: "/var/lib/grafana/dashboards/istio/istio-control-plane-dashboard_rev93.json"
      subPath: "istio-control-plane-dashboard_rev93.json"
    - name: "istio-mesh-dashboard"
      filename: "config/istio-mesh-dashboard_rev93.json"
      mountPath: "/var/lib/grafana/dashboards/istio/istio-mesh-dashboard_rev93.json"
      subPath: "istio-mesh-dashboard_rev93.json"
    - name: "istio-performance-dashboard"
      filename: "config/istio-performance-dashboard_rev93.json"
      mountPath: "/var/lib/grafana/dashboards/istio/istio-performance-dashboard_rev93.json"
      subPath: "istio-performance-dashboard_rev93.json"
    - name: "hyperledger-fabric"
      filename: "config/hyperledger-fabric_rev1.json"
      mountPath: "/var/lib/grafana/dashboards/hyperledger/hyperledger-fabric_rev1.json"
      subPath: "hyperledger-fabric_rev1.json"
    - name: "orderers"
      filename: "config/orderers_rev1.json"
      mountPath: "/var/lib/grafana/dashboards/hyperledger/orderers_rev1.json"
      subPath: "orderers_rev1.json"
    - name: "k8s-cluster"
      filename: "config/k8s-cluster.json"
      mountPath: "/var/lib/grafana/dashboards/k8s/k8s-cluster.json"
      subPath: "k8s-cluster.json"
    - name: "k8s-storage"
      filename: "config/k8s-storage.json"
      mountPath: "/var/lib/grafana/dashboards/k8s/k8s-storage.json"
      subPath: "k8s-storage.json"
    - name: "container"
      filename: "config/container_rev1.json"
      mountPath: "/var/lib/grafana/dashboards/k8s/container_rev1.json"
      subPath: "container_rev1.json"
