apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-{{ include "appname" . }}-{{ include "orgname" . }}
  labels:
    {{- include "gw.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 4101
        name: https-ext-gw
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
      hosts:
        - {{ .Values.fqdn }}
