apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    path: {{ .Values.appBasePath }}
  {{- with .Values.source }}
    {{- toYaml . | nindent 4 }}
  {{- end}}
  destination:
    namespace: argocd
    server: '{{ .Values.destination.server}}'
  {{- with $.Values.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end}}
