apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
{{/*  finalizers:*/}}
{{/*  - resources-finalizer.argocd.argoproj.io*/}}
spec:
  project: {{ .Values.global.project }}
  source:
    path: {{ .Values.global.appBasePath }}
  {{- with .Values.global.source }}
    {{- toYaml . | nindent 4 }}
  {{- end}}
  destination:
    namespace: argocd
    server: {{ $.Values.global.destination.server | quote }}
  {{- with $.Values.global.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end}}
