apiVersion: v1
kind: Service
metadata:
  name: {{ include "hkicl.appname" . }}
  labels:
    {{- include "redis-exporter.labels" . | nindent 4 }}
    svc.hkicl/name: {{ include "hkicl.appname" . }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "redis-exporter.selectorLabels" . | nindent 4 }}
    app.hkicl/name: {{ include "hkicl.appname" . }}
