orgname: org0
mspid: Org0MSP
appname: orderer0
fqdn: orderer0-org0.cdi.testnet
secretvol:
  vol:
    - name: genesis
      # -- Fixture
      # @default -- internal value
      mountPath: /secret/genesis
    - name: tls-orderer0
      # -- Fixture
      # @default -- internal value
      mountPath: /secret/tls
    - name: msp-orderer0
      # -- Fixture
      # @default -- internal value
      mountPath: /secret/msp

timezone: Asia/Hong_Kong

debug:
  broadcast: false
  deliver: false

replicaCount: 1

nodeSelector:
  node.hkicl/nodename: node1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

persistence:
  # -- Fixture
  # @default -- internal value
  enabled: true
  # -- Fixture
  # @default -- internal value
  annotations: {}
  # -- Fixture
  # @default -- internal value
  storageClass: ""
  # -- Fixture
  # @default -- internal value
  accessMode: ReadWriteOnce
  size: 1Gi
  # -- Fixture
  # @default -- internal value
  mountPath: "/var/artifacts"
  # existingClaim: ""

# -- Fixture
# @default -- internal value
image:
  repository: hyperledger/fabric-orderer
  pullPolicy: IfNotPresent

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  # -- Fixture
  # @default -- internal value
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
  # -- trace|debug|info|warning|error|critical|off
  sidecar.istio.io/logLevel: "warning"

# -- Fixture
# @default -- internal value
podSecurityContext: {}
  # fsGroup: 2000

# -- Fixture
# @default -- internal value
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 7050
      targetPort: 7050
      protocol: TCP
      name: tls-request
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: http-metrics

# -- Fixture
# @default -- internal value
istioService:
  enabled: true
  ports:
    - port: 7050
      name: tls-ext-listen-endpoint
      protocol: TLS
      destPort: 7050
    - port: 80
      name: http-ext-metrics
      protocol: HTTP
      destPort: 8443
      match:
      - port: 80
      - uri:
          exact: /healthz

livenessProbe:
  successThreshold: 1
  failureThreshold: 3
  # -- Fixture
  # @default -- internal value
  httpGet:
    scheme: HTTP
    path: /healthz
    port: 8443
  initialDelaySeconds: 30
  periodSeconds: 30

readinessProbe:
  successThreshold: 1
  failureThreshold: 3
  # -- Fixture
  # @default -- internal value
  httpGet:
    scheme: HTTP
    path: /healthz
    port: 8443
  initialDelaySeconds: 30
  periodSeconds: 30

# -- Fixture
# @default -- internal value
configmap:
  enabled: true
  data: "config/*.*"
  mountPath: "/setup"

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
affinity: {}

# -- Fixture
# @default -- internal value
certRootDir: /var/artifacts
# -- Fixture
# @default -- internal value
cryptoDir: crypto-config

# -- Fixture
# @default -- internal value
ordererHome: /var/artifacts/orderer
