orgname: ORGNAME

image:
  repository: hktfp5/eventstore
  pullPolicy: IfNotPresent

podAnnotations:
  # -- Fixture
  # @default -- internal value
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
  # -- trace|debug|info|warning|error|critical|off
  sidecar.istio.io/logLevel: "warning"

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 125m
    memory: 256Mi

timezone: Asia/Hong_Kong

# -- Fixture
# @default -- internal value
appname: cc

# -- Fixture
# @default -- internal value
replicaCount: 1

# -- Fixture
# @default -- internal value
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Fixture
# @default -- internal value
nodeSelector: {}

# -- Fixture
# @default -- internal value
tolerations: []

# -- Fixture
# @default -- internal value
affinity: {}

# -- Fixture
# @default -- internal value
chaincodeAddress: 0.0.0.0:7052

# -- Fixture
# @default -- internal value
service:
  type: ClusterIP
  ports:
    - port: 7052
      targetPort: 7052
      protocol: TCP
      name: tcp-chaincode

# -- Fixture
# @default -- internal value
istioService:
  enabled: true
  port: 7052
  name: tcp-chaincode
  protocol: TCP
  destPort: 7052

# -- Fixture
# @default -- internal value
podSecurityContext: {}
# fsGroup: 2000

# -- Fixture
# @default -- internal value
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# -- Fixture
# @default -- internal value
imagePullSecrets: []

# -- Fixture
# @default -- internal value
nameOverride: ""

# -- Fixture
# @default -- internal value
fullnameOverride: ""

# -- Fixture
# @default -- internal value
serviceAccount:
  create: true
  annotations: {}
  name: ""
