apiVersion: v2
name: auth-server
description: Experimental auth server
type: application
version: 0.1.0
appVersion: "0.0.6"
icon: "https://raw.githubusercontent.com/rtang03/rtang03/main/dashslab_icon.jpg"
annotations:
  artifacthub.io/changes: |
    - "initial commit"
  artifacthub.io/maintainers: |
    - name: "rtang03"
      email: "ask@dashslab.com"
  artifacthub.io/prerelease: "true"
